travis:
  secure:
    BINSTAR_TOKEN: S1Y4Z7YryWXuhhm7I9DsODv0wYxw3JUS3kCxyy4qDuO/8cfiw/SwSKVmiot3cLqII+Vf86NKWZ/yJm/BS7hItYcp9tHyI5fd81GXP9PJRu3Z7PZhyxAHpCfGtJRCMCSLZeLNiejfg5D1cxc/l2ATX9h20bSheFyHGa7PMs7ZtpjxfrQbIzgFN+UlF4L5u63gW3srkoylQZVdQlngjaC8E4vh3qw/IGKZVr/gmJa37mfyKj9lHqLrAgo7Sx0qKh3BvpJorTwlv9l4G0U9SsbrBTow+f2Ps7sKFcay/2Wv0dCd64/E49ohnsYzjWUBip38Ec8i6KO9oH+qJl/29xDXZKOahK4B2IHmxaKmwNLEPkrh5f6hpmstHWBDSQqfGZc9R1kGcQpwpYOh/8NqunoTcsXER/1i0FILadRd3C6mPn8T0WwOLDI/Tpe5Xx221iWSgH+4YxijIPRnWV3kFUBff+MHUIu7UONkrmUh5qiVzXBLgCgbdLuuZLWcoMNzBMPnB5QinxsxrgPxGt9NNn7M7vKaqnPY/O1vPb2fsN67Ij1JqYfxUSfjLak3XaN8wpGDsWJXgSBlPMmlc9hqZO+hWSa2qSd0Yhm9nxeHfxmbCJwguEZRpOxqvoOayH/+4iY1DIWMJd/7eiIjh+tSMYH6Rbih6ro6/162feP+4e+VKV8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
